# Generated by Django 3.2.4 on 2021-06-13 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Microtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('target_date', models.DateField()),
                ('description', models.TextField(max_length=1000)),
                ('upload_job_sample', models.FileField(max_length=500, upload_to='')),
                ('upload_job_instructions', models.FileField(max_length=500, upload_to='')),
                ('job_quantity', models.IntegerField()),
                ('number_of_people_required', models.IntegerField()),
                ('skills', models.CharField(max_length=500)),
                ('job_cost', models.IntegerField(help_text='job cost in AED')),
            ],
        ),
        migrations.CreateModel(
            name='MTOJobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MTORoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MTOJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.IntegerField(help_text='related to MTO')),
                ('due_date', models.DateField()),
                ('assigned_date', models.DateField()),
                ('fees', models.FloatField()),
                ('rating_evaluation', models.IntegerField()),
                ('payment_status', models.IntegerField()),
                ('completed_date', models.DateField()),
                ('output_path', models.FileField(upload_to='')),
                ('evaluation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.evaluationstatus')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.microtask')),
            ],
        ),
        migrations.CreateModel(
            name='MTOAdminUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL)),
                ('varal_role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.mtoroles')),
            ],
            options={
                'verbose_name_plural': 'MTO Admin Users',
            },
        ),
        migrations.AddField(
            model_name='microtask',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.mtojobcategory'),
        ),
        migrations.AddField(
            model_name='evaluationstatus',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.microtask'),
        ),
    ]
